#!/usr/bin/env node
/**
 * Generates deploy-vps.config.json + site/.env.vps.local with all secrets.
 * Zero manual .env editing.
 *
 * Usage:
 *   npm run setup:vps
 *   npm run setup:vps -- --host 203.0.113.10
 *   npm run setup:vps -- --bootstrap
 *   npm run setup:vps -- --formspree mknnvgep
 */
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const defaultsPath = resolve(root, "scripts/setup-vps.defaults.json");
const configPath = resolve(root, "scripts/deploy-vps.config.json");
const envPath = resolve(root, "site/.env.vps.local");
const credsPath = resolve(root, "scripts/vps-generated-credentials.txt");

function loadJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function parseArgs(argv) {
  const out = { bootstrap: false, host: null, domain: null, formspree: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--bootstrap") out.bootstrap = true;
    else if (a === "--host" && argv[i + 1]) out.host = argv[++i];
    else if (a === "--domain" && argv[i + 1]) out.domain = argv[++i];
    else if (a === "--formspree" && argv[i + 1]) out.formspree = argv[++i];
    else if (!a.startsWith("-") && !out.host) out.host = a;
  }
  return out;
}

function secretBase64(bytes = 32) {
  return randomBytes(bytes).toString("base64");
}

function secretAlnum(length = 24) {
  const chars =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*";
  const buf = randomBytes(length);
  let s = "";
  for (let i = 0; i < length; i++) {
    s += chars[buf[i] % chars.length];
  }
  return s;
}

function siteUrl(domain) {
  const d = domain.replace(/^https?:\/\//, "").replace(/\/$/, "");
  return `https://${d}`;
}

function buildEnvFile({ domain, databaseUrl, appPort, secrets, formspreeId }) {
  const origin = siteUrl(domain);
  const contactBlock = formspreeId
    ? `FORMSPREE_ENDPOINT="https://formspree.io/f/${formspreeId}"`
    : `CONTACT_WEBHOOK_URL="${secrets.contactWebhook}"`;

  return `# AUTO-GENERATED by npm run setup:vps — do not commit
# ${new Date().toISOString()}

NODE_ENV=production
PORT=${appPort}

DATABASE_URL="${databaseUrl}"

AUTH_SECRET="${secrets.authSecret}"

AUTH_URL="${origin}"
NEXT_PUBLIC_SITE_URL="${origin}"

${contactBlock}

GROWTH_ADMIN_PASSWORD="${secrets.growthAdmin}"
GROWTH_DEMO_PASSWORD="${secrets.growthDemo}"

NEXT_PUBLIC_CONTACT_PHONE_RAW="+963953562654"
NEXT_PUBLIC_CONTACT_PHONE_DISPLAY="+963 953 562 654"
NEXT_PUBLIC_WHATSAPP_E164="+963953562654"
`;
}

function sshTarget(cfg) {
  return `${cfg.user}@${cfg.host}`;
}

function runSsh(cfg, script) {
  const port = cfg.port ?? 22;
  const r = spawnSync(
    "ssh",
    [
      "-p",
      String(port),
      "-o",
      "BatchMode=yes",
      "-o",
      "ConnectTimeout=15",
      sshTarget(cfg),
      "bash -s",
    ],
    { input: script, encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] },
  );
  if (r.status !== 0) {
    console.error(r.stderr || r.stdout);
    return false;
  }
  if (r.stdout) process.stdout.write(r.stdout);
  return true;
}

function bootstrapServer(cfg, defaults) {
  const dbPass =
    defaults.databaseUrl.match(/:([^@]+)@/)?.[1] ?? "Tenegta2025Secure";
  const escaped = dbPass.replace(/'/g, "''");
  const script = `
set -e
if ! command -v node >/dev/null 2>&1; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi
if ! command -v pm2 >/dev/null 2>&1; then
  npm install -g pm2
fi
if command -v psql >/dev/null 2>&1; then
  sudo -u postgres psql -v ON_ERROR_STOP=0 <<'SQL' || true
DO \\$\\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'tenegta_user') THEN
    CREATE USER tenegta_user WITH PASSWORD '${escaped}';
  END IF;
END
\\$\\$;
SELECT 'CREATE DATABASE tenegta_db OWNER tenegta_user'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'tenegta_db')\\gexec
GRANT ALL PRIVILEGES ON DATABASE tenegta_db TO tenegta_user;
SQL
fi
mkdir -p ${cfg.remotePath}
if [ ! -d ${cfg.remotePath}/.git ]; then
  git clone https://github.com/sadeksobeg/ten-w.git ${cfg.remotePath} || true
fi
echo "Bootstrap OK"
`;
  console.log("\n==> Server bootstrap (Node, PM2, PostgreSQL, git)...\n");
  return runSsh(cfg, script);
}

const args = parseArgs(process.argv.slice(2));
const defaults = loadJson(defaultsPath);

const deployConfig = {
  host: args.host ?? defaults.host,
  user: defaults.user,
  port: defaults.port,
  remotePath: defaults.remotePath,
  branch: defaults.branch,
  pm2Name: defaults.pm2Name,
  gitRemote: defaults.gitRemote,
};

const domain = args.domain ?? defaults.domain;
const secrets = {
  authSecret: secretBase64(32),
  growthAdmin: secretAlnum(28),
  growthDemo: secretAlnum(28),
  contactWebhook: "https://httpbin.org/post",
};

const envBody = buildEnvFile({
  domain,
  databaseUrl: defaults.databaseUrl,
  appPort: defaults.appPort,
  secrets,
  formspreeId: args.formspree,
});

writeFileSync(configPath, `${JSON.stringify(deployConfig, null, 2)}\n`, "utf8");
writeFileSync(envPath, envBody, "utf8");

const contactLine = args.formspree
  ? `Formspree: https://formspree.io/f/${args.formspree}`
  : `Contact (test webhook): ${secrets.contactWebhook}`;

const summary = `T.E.N.E.G.T.A — VPS setup generated ${new Date().toISOString()}
============================================================

SSH: ${deployConfig.user}@${deployConfig.host}:${deployConfig.port}
Path: ${deployConfig.remotePath}
Site: ${siteUrl(domain)}

Growth admin password: ${secrets.growthAdmin}
Growth demo password:  ${secrets.growthDemo}

AUTH_SECRET: ${secrets.authSecret}

${contactLine}

Files:
  scripts/deploy-vps.config.json
  site/.env.vps.local

Deploy: npm run deploy:vps
`;
writeFileSync(credsPath, summary, "utf8");

console.log("\n✅ VPS config generated automatically\n");
console.log(`   ${configPath}`);
console.log(`   ${envPath}`);
console.log(`   ${credsPath}  ← passwords saved here\n`);

if (args.bootstrap) {
  const ok = bootstrapServer(deployConfig, defaults);
  if (!ok) {
    console.error(
      "Bootstrap SSH failed. Fix SSH access, then: npm run setup:vps -- --bootstrap\n",
    );
    process.exit(1);
  }
}

console.log("Next: npm run deploy:vps\n");
